universe        = vanilla
executable      = path/to/pipeline.sh
arguments       = path/to/configfile.yml

log             = path/to/condor_logs/pipeline_$(Cluster)_$(Process).log
output          = path/to/condor_logs/pipeline_$(Cluster)_$(Process).out
error           = path/to/condor_logs/pipeline_$(Cluster)_$(Process).err

request_cpus    = 16
request_memory  = 128GB
request_disk    = 150GB

getenv          = True

queue 1